run:
  timeout: 2m

linters:
  enable:
    - revive

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA(4003|1019|5011):"

  include:
    - EXC0012
    - EXC0014

linters-settings:
  exhaustruct:
    # List of regular expressions to exclude struct packages and names from check.
    # Default: []
    exclude:
      # public libs
      - "^github.com/grafana/$"


